[vms.paracord1]
droplet_id = 564_805_964
public_ip = "143.198.231.232"
private_ip = "10.124.0.2"
provisioned_at = "2026-04-14T04:33:49.143Z"
hermes_installed = true
hermes_installed_at = "2026-04-14T06:41:35.256Z"

[agents.cooper]
vm_name = "paracord1"
linux_user = "hm-cooper"
last_synced_at = "2026-04-16T07:39:30.393Z"
last_pulled_at = "2026-04-15T21:42:17.970Z"
hermes_profile_created = true
gateway_installed = true

[agents.troy]
vm_name = "paracord1"
linux_user = "hm-troy"
last_synced_at = "2026-04-14T16:58:07.137Z"
last_pulled_at = "2026-04-14T17:43:31.615Z"
hermes_profile_created = true
gateway_installed = true
